name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set-Up
      run: sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl

    - name: Install Rustup
      run: |
        rustup install nightly-2021-12-13
        rustup default nightly-2021-12-13
        rustup target add wasm32-unknown-unknown

    - name: Setup Cache
      uses: actions/cache@v2
      with:
        path: |
          ./target/
          ~/.cargo/git
          ~/.cargo/registry
        key: ${{ runner.os }}-build

    - run: cargo build --release

    - run: ./target/release/nftmart-node --version
      name: show version

    - name: archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          ./target/release/nftmart-node
          ./target/release/nftmart-aura-node

    - run: cargo doc

    - name: archive doc
      uses: actions/upload-artifact@v2
      with:
        name: doc
        path: |
          ./target/doc/

  push:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      name: download artifacts
      with:
        name: build
        path: ./bin/

    - run: docker build -f .github/Dockerfile -t nftmart/node:${{ github.sha }} .
      name: docker build

    - run: docker run nftmart/node:${{ github.sha }} --version
      name: show version

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - run: docker push nftmart/node:${{ github.sha }}
      name: docker push

    - run: |
        docker tag nftmart/node:${{ github.sha }} nftmart/node
        docker push nftmart/node
      if: github.ref == 'refs/heads/master'
      name: docker push latest
